### ISSUE TITLE
Metadata Extract error based on privileges for Denodo

### ISSUE THREAD

**Issue by tylerinsd** [Informatica-EIC/Custom-Scanners#29]
We have created a user to extract from Denodo and that user has Connect and Metadata across all VDB's. It appears that only admin based accounts can traverse the metadata and properly leverage the stored procedures.

When we get the following error:

D:\Informatica\denodoCustomScanner>D:\Informatica\10.2.2\jre\bin\java -cp "denodoCustomScanner.jar;l
ib/*" com.infa.edc.scanner.jdbc.DenodoScanner denododev.properties agreeToDisclaimer > D:\Informatic
a\denodoCustomScanner\command_dev.txt
java.sql.SQLException: The user does not have WRITE privileges on the datasource 'ds_BSSH-API_get-bi
osample_biosample-id'
        at com.denodo.vdb.jdbcdriver.printer.VDBJDBCPrinter.format(VDBJDBCPrinter.java:158)
        at com.denodo.vdb.jdbcdriver.dao.DAOVDBProxy.execute(DAOVDBProxy.java:623)
        at com.denodo.vdb.jdbcdriver.dao.DAOVDBProxy.execute(DAOVDBProxy.java:586)
        at com.denodo.vdb.jdbcdriver.dao.DAOVDBProxy.execute(DAOVDBProxy.java:580)
        at com.denodo.vdb.jdbcdriver.dao.DAOVDBProxy.execute(DAOVDBProxy.java:575)
        at com.denodo.vdb.jdbcdriver.VDBJDBCStatement.executeQuery(VDBJDBCStatement.java:321)
        at com.infa.edc.scanner.jdbc.DenodoScanner.collectDataSourcesforSchema(DenodoScanner.java:26
1)
        at com.infa.edc.scanner.jdbc.DenodoScanner.getSchemas(DenodoScanner.java:201)
        at com.infa.edc.scanner.jdbc.DenodoScanner.getCatalogs(DenodoScanner.java:177)
        at com.infa.edc.scanner.jdbc.GenericScanner.run(GenericScanner.java:251)
        at com.infa.edc.scanner.jdbc.DenodoScanner.main(DenodoScanner.java:158)
java.sql.SQLException: The user does not have WRITE privileges on the datasource 'ds_BSSH-API_get-bi
osamples'
        at com.denodo.vdb.jdbcdriver.printer.VDBJDBCPrinter.format(VDBJDBCPrinter.java:158)
        at com.denodo.vdb.jdbcdriver.dao.DAOVDBProxy.execute(DAOVDBProxy.java:623)
        at com.denodo.vdb.jdbcdriver.dao.DAOVDBProxy.execute(DAOVDBProxy.java:586)
        at com.denodo.vdb.jdbcdriver.dao.DAOVDBProxy.execute(DAOVDBProxy.java:580)
        at com.denodo.vdb.jdbcdriver.dao.DAOVDBProxy.execute(DAOVDBProxy.java:575)
        at com.denodo.vdb.jdbcdriver.VDBJDBCStatement.executeQuery(VDBJDBCStatement.java:321)
        at com.infa.edc.scanner.jdbc.DenodoScanner.collectDataSourcesforSchema(DenodoScanner.java:26
1)
        at com.infa.edc.scanner.jdbc.DenodoScanner.getSchemas(DenodoScanner.java:201)
        at com.infa.edc.scanner.jdbc.DenodoScanner.getCatalogs(DenodoScanner.java:177)
        at com.infa.edc.scanner.jdbc.GenericScanner.run(GenericScanner.java:251)
        at com.infa.edc.scanner.jdbc.DenodoScanner.main(DenodoScanner.java:158)

**Comment by darren-wrigley** [comment]
this appears to be the same as #28 - https://github.com/Informatica-EIC/Custom-Scanners/issues/28 

the problem is how Denodo is working internally - they are forcing WRITE privileges to be able to execute a desc (describe) for datasources - see notes on  issue #28
